### ISSUE TITLE
Short name of Bitcoin Cash

### ISSUE THREAD

**Issue by jjz** [Bitcoin-ABC/bitcoin-abc#104]
Bitcoin Cash's short name is BCC,  But BCC have same name with Bitconnect's digital assets. In the community of bitcoin cash in China, BCC has been renamed BCH, I suggest using the same name:BCH.
This is Okex's announcement :[https://support.okex.com/hc/en-us/articles/115002562572-OKEx-Launches-New-Futures](https://support.okex.com/hc/en-us/articles/115002562572-OKEx-Launches-New-Futures) ,And BTC Pool,Bitkan has changed Bitcoin Cash's name to BCH.

**Comment by seoulbit** [comment]
Most exchanges I use favor BCH, I agree with using that. BCC and bcash seem to be used only by scammers and cynics.

**Comment by jli225** [comment]
The introduction of short name 'BCH' by some exchanges was not because of bitconnect. 

Although I don't dislike the short name 'BCH', we should know it was originally introduced as a political trick. So we much be very vigilant about the result of feeding those bad actors.

So I think this proposal is unnecessary. Similarly, Bitcoin remained 'btc' when it's called 'XBT' by ppl out of cryptocurrency world.

NACK.

ps: It's interesting to see that other services changes the short name to avoid so-called user confusion, only because Bitfinex introduced it for no good reason and refuse to change it anyway. Similar thing happened to the war that who should remain the brand name: 'Bitcoin Segwit1x' or 'Bitcoin Segwit2x'. I know such behavior is normal in monkey groups yet didn't expect to see it happen in human society.

**Comment by cool007zqw** [comment]
In fact I see Chinese use BCC more than BCH, currently.
I think it's ok to use BCH to avoid confusion since BCC is more considered as BitConnect in most exchanges.

Such a difference in name would not change much on the future of Bitcoin Cash.

**Comment by samysousa** [comment]
I have not seen a single place where BCC is used for Bitcoin Cash, it`s BCH everywhere. I am certain that BitcoinABC is regarded as "unligitimate" by some because of this naming that is not recognized.

**Comment by jli225** [comment]
@samysousa "by some" by whom? Blockstream Core doesn't have and shouldn't have any power here.

It's confusing that you spoke for some  people who don't even exist or at least don't belong to our community.

**Comment by schancel** [comment]
This seems to have settled on `BCH`.  Closing this issue as a result.
