### ISSUE TITLE
Unable to build v0.16.1 on Debian Jessie 8

### ISSUE THREAD

**Issue by gituser** [Bitcoin-ABC/bitcoin-abc#120]
### Describe the issue
Unable to build `v0.16.1` on Debian Jessie 8

#### If so, please list the steps to reproduce below:
Yes
I'm doing this to build bitcoinABC:
```
#!/bin/bash
VER=$(git describe --tags)
daemon=$(pname=$(pwd); echo ${pname##/*/})
make clean
make distclean
./autogen.sh
./configure --without-miniupnpc --without-gui --with-incompatible-bdb --disable-zmq 
if [ "$?" != 0 ]; then
    echo "Configure failed"
    exit 1;
fi
make -j8
```

### Expected behaviour
BitcoinABC should be built successfully even on Debian Jessie

### Actual behaviour
Doesn't build.

### Machine specs:
- OS: Debian Jessie 8 (fully updated)
- gcc/g++: Debian Jessie 8 stock - g++ 4.9.2-2
- boost:  Debian Jessie 8 stock - libboost-all - 1.55.0.2

### Any extra information that might be useful in the debugging process.
Here is a link to the build errorlog:
https://paste.fedoraproject.org/paste/S4Dd~iuMgC7MdlEM39~QSg

If I apply workaround of commenting `//friend constexpr Amount operator*(const double a, const Amount b) = delete;` in `src/amount.h` on line 76 and add `--without-seeder` bitcoinabc isn't building either, here is a log: https://paste.fedoraproject.org/paste/sEtj5dUdUhhv0TeQlChVEg

### What should be done?

Many people still using Debian Jessie 8 as a distribution. So would be nice instead of breaking BitcoinABC for compilation make it compatible with Debian Jessie 8.

**Comment by gituser** [comment]
any update on this?

**Comment by ftrader** [comment]
I was able to build it on a Debian 8 derivative distribution - so this *could* work for your system too.
Firstly, I applied the 'friend' commenting you did, then I did a 'depends' build first, the results of which I used later for the actual bitcoind build.

Build the dependencies (see also depends/README.md for more info):

`CC=/usr/bin/gcc CXX=/usr/bin/g++ make -j10 -C depends HOST=x86_64-linux-gnu NO_QT=0 NO_UPNP=1 DEBUG=1`

Now to build the ABC software itself:

`sh autogen.sh`

`./configure CC=/usr/bin/gcc CXX=/usr/bin/g++ --prefix=$(pwd)/depends/x86_64-pc-linux-gnu --with-gui=qt4 --enable-cxx --with-incompatible-bdb --with-seeder=yes`

`make -j 4`

This failed in cashaddrenc_tests.cpp due to another problem that someone else already pointed out (lack of an operator definition in the older Boost).

This patch can be used to overcome that problem: https://gist.github.com/ftrader/418ff12c43f1274c662008cc7d1be491

After that the build succeeded. Beware though that a `make install` will install the build products into the `--prefix` folder that has been specified. There seems to be no good build target that extracts a tarball from this which would be suitable for distribution or easier deployment elsewhere. This is handled by the gitian build scripts at the moment.

**Comment by gituser** [comment]
Thanks @ftrader 
It seems though dependencies build - builds different boost out there and openssl and other libs like lidb-4.8 will they be used by resulting binary?

I was able to build using your method, thanks!

Still needs a proper solution for Debian Jessie 8 users from the developers.  Ping @deadalnix.

**Comment by schancel** [comment]
Closing as outdated.  If this is still an issue with 0.17.0 please reopen.
