### ISSUE TITLE
How to spent a segwit output in bitcoincash?

### ISSUE THREAD

**Issue by phuongnd08** [Bitcoin-ABC/bitcoin-abc#231]
A segwit output locking script means anyone can spent in Bitcoin Cash.
But it seems that a dedicated miner is necessary to deliberately mine a Bitcoin Cash transaction that spent such segwit output. (this is why this exists: https://bch.btc.com/docs/help/bch_segwit_recovery)

Why isn't it possible for any one just simply recover the fund? Why do we even need to submit 10% to a miner here, given the current status of the Bitcoin Cash network?

**Comment by amadeobrands** [comment]
I do not really understand your exact qwestion? You want a more easy way to recover a segwit transaction that is send to a Bitcoin Cash adress or the other way around? 

You will not be able to do that easily even if you have the private key Since bitcoin cash doesn't support Segwit, so you have to edit source code and mine that transaction by yourself.

Helpful links:
https://medium.com/bitclave/bitcoin-cash-segwit-hack-e82c7029f841 
https://www.reddit.com/r/Bitcoin/comments/7eixcu/recovering_bch_sent_to_segwit_addresses/?st=jee4ic5o&sh=11e0ebf5

**Comment by phuongnd08** [comment]
Okay, I get it now. So given BCH was incorrectly sent to a segwit, I can simply craft a valid transaction and cast it to the network then? Miners or nodes won't reject such transaction?

**Comment by phuongnd08** [comment]
@jasonbcox I sent you a mail with a particular case about spending BCH in segwit address.

**Comment by phuongnd08** [comment]
@amadeobrands Sorry I should have emailed you instead. @jasonbcox Could you please forward my email to @amadeobrands

**Comment by phuongnd08** [comment]
Okay after reading through again, here is my recap:

Even with private key, I won't be able to successfully spend a BCH output mistakenly sent to my segwit address. The transaction can't be broadcasted to network (https://twitter.com/khannib/status/932715632134586369).

The reason that btc.com can spend a BCH output because they have mining power.

On a related topic, when I try to relay a transaction that spend a BCH segwit output, I get this:

64: non-mandatory-script-verify-flag (Script did not clean its stack)

Which is confusing. It should have told me that "As a regular user you can't spend segwit output"
