### ISSUE TITLE
Network Split Attack using deep reorg protection

### ISSUE THREAD

**Issue by Haatschii** [Bitcoin-ABC/bitcoin-abc#282]
So as far as I understand Bitcoin ABC recently added deep reorg protection in the sense that every block with depth 10 or more becomes immutable and protected from chain reorganisation. This in particular means that a node will stay on a minority chain if switching to the majority chain requires a reorg of 10 or more blocks. In the following I outline some thoughts on a possible attack which exploits this behaviour to irreversibly split the network.

The assumption of this attack is that there is an attacker with a significant share of the hash power at his disposal (which in my understanding is also the assumption that lead to the implementation of deep reorg protection in the first place). The attack takes place as follows:

- At the current block X the attacker starts mining a private chain (called attack chain in the following), competing with the chain build by the honest miners (called honest chain in the following).

- Given a sufficient share of the hash rate the attacker has a chance to reach a chain of length 10 (measured from X), before the honest miners do. If he fails he simply abandons his chain and starts again. 

- If he succeeds he waits for the honest chain to reach length 9 (again measured from X) and when it does he tries to find the 10th block on the honest chain first. Again given a sufficient share of the hash rate he has a chance for being successful.

- If he is successful he publishes his private chain to one half of his network connections and the newly found 10th block the the other half. (More elaborately he would probably give the private chain a small head start due to the larger propagation time.)

- All nodes receiving the private chain first are currently 9 blocks away from X (which is where the honest chain and the attack chain diverge), therefore they will allow a reorg to the attack chain as it is one block longer and the reorg depth is below 10. After the reorg X is at depth 10, therefore the deep replay protection prevents switching back to the honest chain.

- All nodes receiving the 10th block on the honest chain first will append said block to their chain, thereby moving X to depth 10. Consequently the deep reorg protection prevents those nodes to ever switch to the attack chain.

- If the attacker is able to simultaneously publish the attack chain and the 10th block on the honest chain to a large number of nodes, the network will split into two parts, one following the honest chain and one following the attack chain. The deep reorg protection prevents both parts of the network to rejoin, causing an irreversible chain split (apart from manual interaction and consent finding). 

The immediate effects are speculation, but chaos and severe drop in usability, value and trust in the Bitcoin Cash network is guaranteed. Possibly even worse than what would happen in case of a deep reorg.

It is in the middle of the night here, so i skip doing the Math on the success probabilities of this attack. However I conjecture that chances become very reasonable if the attacker has 50% or more of the hash rate.

Edit: As pointed out in the reddit discussion the new rules for extra PoW required for a reorg make this attack more expensive, i.e. the attack would need a chain twice as long as the honest chain. But this is basically the same PoW needed by an attacker to pull an reorg attack, i.e. the scenario justifying the deep reorg protection in the first place.

**Comment by Pheromon** [comment]
As Satoshi explained in one of his first emails: https://satoshi.nakamotoinstitute.org/emails/cryptography/6/

> It is strictly necessary that the longest chain is always considered the valid one. Nodes that were present may remember that one branch was there first and got replaced by another, but there would be no way for them to convince those who were not present of this. We can't have subfactions of nodes that cling to one branch that they think was first, others that saw another branch first, and others that joined later and never saw what happened. The CPU power proof-of-work vote must have the final say. The only way for everyone to stay on the same page is to believe that the longest chain is always the valid one, no matter what.

**Comment by monacoinproject** [comment]
I introduce our solution.
Monacoin can checkpoint delivery that using the Alert system.
It will be centralized, but it is better than chain split.
And the cost of implementing this feature is minimal.
This is a temporary measure.

monacoinproject/monacoin@43e9f59  Monacoin: Resurrect the alert system
monacoinproject/monacoin@773eb50  Monacoin: Add checkpoint RPC
monacoinproject/monacoin@fada3ee  Monacoin: Add volatile-checkpoint
monacoinproject/monacoin@fc4f4b3  Monacoin: Add Alert-checkpint command
monacoinproject/monacoin@cfe4ff2  Monacoin: Disable alert-cmd with old monacoind
monacoinproject/monacoin@f10cf9f  Monacoin: Improved alert-cmd
monacoinproject/monacoin@4b9d0c3  Monacoin: Add maxnum argument to dumpcheckpoint rpc
monacoinproject/monacoin@0eded4a  Monacoin: Alert-checkpint is enabled by default
monacoinproject/monacoin@8221d0c  Monacoin: Monacoin: Improved alert-cmd and add copyright
monacoinproject/monacoin@c75a7c9  Monacoin: normal-alert can't cancel alert-command
monacoinproject/monacoin@454a23c  Monacoin: Monacoin: Add sub alert key
monacoinproject/monacoin@05877ce  Monacoin: Monacoin: fix wrong comparison

**Comment by TronBlack** [comment]
Haatschii, this is accurate.  But it still has a number of advantages.
1. It changes from a 51%+ attack to a 51%+ attack combined with a timing attack which increases the difficulty of the attack.
2. It removes some of the financial incentives for doing the attack.  If your replacement chain isn't selected by the community consensus because the attack chain contains double-spends that try to cheat a merchant or exchange, then the attack does not pay off.  The attacker pays for the attack and also assumes a high risk of failure of the attack.
3. It gives a definitive number of confirmations for acceptance.
4. In the case of a platform (like Ravencoin) where the value of the transferred assets may exceed the value of the coinbase reward, it provides an assurance after X blocks that the chain won't be automatically replaced.  Most other blockchains, including Bitcoin can't make that assurance as they remain probabilistic.
5. Once the reason for the split is determined and manual steps are taken to gain consensus, all honest transactions will be returned to the mempool and added to the consensus chain - making everyone whole.  Unless there is a conflict (double-spend), which will then be detected and may help determine which chain is the "honest" chain.

There are two recovery modes:
1. It was an attack.  In which case it would be good to determine the reason and the culprit, and manually accept the "honest" chain.
2. It was a sub-sea cable break or similar with no dishonest activity in which case acceptance of all transactions from both chains is an acceptable resolution.

Because the difficulty of the attack is significantly increased, and the probability of a double-spend working in the attacker's favor is greatly reduced, it eliminates the incentives for malicious behavior for financial gain.  Attacks by nation states or purely malicious actors are made more difficult, but certainly possible as you've pointed out.

With the additions made by Ravencoin of ensuring the chain is fully synced, and the node is "well-connected", it eliminates an additional attack vector of tricking nodes into forking before being fully synced.  It is only "surprise" re-orgs that are rejected.

I've been told that at least one attack was thwarted on a different coin that adopted Ravencoin's deep reorg prevention code.

**Comment by dgenr8** [comment]
These schemes are all pointless when "manual recovery" is part of the solution.  If you want to fork manually to a less-work chain, you can always just do that.

If you're worried about hash with nothing better to do than nuisance attacks, concentrate more on not listening to the people who run your network.
