### ISSUE TITLE
RPC port config being ignored after 0.19.5

### ISSUE THREAD

**Issue by jeansouza** [Bitcoin-ABC/bitcoin-abc#323]
The application is aparently ignoring the `rpcport` configuration. This problem showed after I started to use the version 0.19.5.

#### Expected behaviour
I'm running a testnet full node and want the RPC interface to listen to port 8332.

#### Actual behaviour
Even with the option setted in my config file, the application uses the port 18332.

#### What version of bitcoin-abc are you using?
0.19.5

**Comment by dangelkov** [comment]
Same problem here.
Version 0.19.5 the rpcbind option in config file is completely ignored.
if you specify it as runtime parameter it opens the port and then it closes it with an error messege:
"Error: Unable to bind to 0.0.0.0:18333 on this computer. Bitcoin ABC is probably already running.
Error: Failed to listen on any port. Use -listen=0 if you want this."

**Expected behavior:**
Not to brake fundamental settings with every fucking release

**Actual behavior**
Random problems every time this piece of shit is upgraded

**Comment by lutk** [comment]
0.19.6
the same problem

**Comment by dangelkov** [comment]
So it turns out that this is happening only when you are in testnet. The debug.log states it very clear. For the rpcport and rpcbind to be considered, they should be in test section in the config file.
Also it somehow documented in the release notes for the version that introduced this (0.18.8):

**Comment by jeansouza** [comment]
Yes, now I see. But like you said @dangelkov , this is very poorly documented.

**Comment by jasonbcox** [comment]
@dangelkov is correct.  The debug.log should provide sufficient instructions for fixing the issue.

The release notes could have been clearer.  We'll be sure to include more thorough notes for changes like this in the future.
