### ISSUE TITLE
Revert codestyle changes

### ISSUE THREAD

**Issue by prusnak** [Bitcoin-ABC/bitcoin-abc#33]
Making code style changes for no apparent reason is not a good thing to do, e.g. https://github.com/Bitcoin-ABC/bitcoin-abc/commit/0d79bc46200f26a97494fe2123a08db42b8d0dd9

It is making backporting features/bug fixes from mainline (Bitcoin Core) hard.

@ftrader told us he wants to apply our Bitcore patches on top of ABC code (see https://www.reddit.com/r/TREZOR/comments/6ompvc/do_trezor_will_support_uahf_in_the_same_you_said/dkmdjgn/) but after these codestyle changes, merging the Bictore patches will be almost impossible task (certainly not doable until August 1st, when you do want to have this ready).

I suggest to revert all formatting patches, such as:

![34233170-be65-45ad-8c21-83345f395833](https://user-images.githubusercontent.com/42201/28669232-b2957842-72d3-11e7-9267-5a2b51bfb8ba.jpg)

**Comment by deadalnix** [comment]
This is not happening.

**Comment by prusnak** [comment]
Pride is a poor substitute for intelligence.

**Comment by deadalnix** [comment]
And ad hominems are poor substitutes for arguments.

Many companies and open source projects have a coding standards. Bitcoin has none and it's a complete mess. The good news is that Bitprim already has the set of patches you want, so it's all good.

**Comment by runn1ng** [comment]
I am not against code style changes per se, **but** this will make merging any patches here significantly harder.

Not only bitcore patches, but any safety patches to bitcoin core. And let's face it, bitcoin core is more active than your repo (and will for foreseeable future), so any security changes will be *much* harder to merge back here, just because of slightly changed coding style.
