### ISSUE TITLE
Make check fails on MacOS

### ISSUE THREAD

**Issue by dzwiener** [Bitcoin-ABC/bitcoin-abc#340]
### Describe the issue
Make check fails

#### If so, please list the steps to reproduce below:
1. Follow make-osx.md file until you reach make check

### Expected behaviour
Tell us what should happen
The tests should pass

### Actual behaviour
Tell us what happens instead
The tests fail

### What version of bitcoin-abc are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.
38c6c4e33b29c15dd17d193e702d85833378ccb8

### Machine specs:
- OS: MacOS
- CPU: 2.8 GHz Intel Core i7
- RAM: 16 GB 1600 MHz DDR3
- Disk size: 500 GB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.
[test-suite.log](https://github.com/Bitcoin-ABC/bitcoin-abc/files/3527009/test-suite.log)

**Comment by Fabcien** [comment]
This should be fixed by https://reviews.bitcoinabc.org/D3936.
You can still build and run the software, the issue comes from an incompatibility with the Qt minimal platform on macOS. You can still run the tests if you need it with `./src/qt/test/test_bitcoin-qt -platform cocoa`, they must they must all pass.

**Comment by Fabcien** [comment]
Closing this as it has been released in 0.20.1.
