### ISSUE TITLE
0.21.3 glibc dependency issue

### ISSUE THREAD

**Issue by Saicere** [Bitcoin-ABC/bitcoin-abc#376]
The release binaries of 0.21.3 bumps the required version of glibc to 2.18, which makes it unusable on a widely used server-class Linux distro, specifically CentOS 7. Running it will just produce the error message:

`./bitcoind: /lib64/libc.so.6: version GLIBC_2.18 not found (required by ./bitcoind)`

Compared to the available version:

`rpm -q glibc`
`glibc-2.17-292.el7.x86_64`

CentOS 7 and by extension RHEL 7 comes with glibc 2.17, which as it is a fundamental system library cannot be updated to a more recent version, at least not without ugly and potentially system-breaking hacks. As per RedHat/CentOS policy, this library does not receive major updates for the lifetime of the system.

While the recently released CentOS 8 comes with a more recent version (2.28), as CentOS 7 is not EOL until [June 30th 2024](https://wiki.centos.org/About/Product), and as it is one of the most if not the most widespread server-class Linux distros, it should probably be supported until then.

As a reference, Core is targeting glibc 2.17 for this specific reason; see [#17538](https://github.com/bitcoin/bitcoin/pull/17538).

Note that 2.17 will still make it unusable on CentOS 6 (EOL November 2020) as it uses glibc 2.12,  but as Core is also dropping support for this, maintaining that support might not be worth the effort.

**Comment by Saicere** [comment]
Update: this also applies to 0.21.4.

**Comment by Fabcien** [comment]
Bitcoin ABC is currently checked for compatibility against glibc 2.19, which is already more than 6 years old.

I am sorry that recent versions are now incompatible with CentOS 7.
We try to keep our versions requirement as low as possible for broader compatibility, but at the same time we need to make sure that our code meets our quality standard, and using the modern features allow us to improve the software reliability, performance and maintainability.
As a consequence there is currently no plan to extend the support to glibc 2.17.

This is not a solution to your problem, but please take into account that:
 - Previous 0.21.x versions are ready for the may upgrade,
 - We aim to be compatible with CentOS 8, which is available since last september.

**Comment by rayeaster** [comment]
@Fabcien so it means latest release 0.21.4 (which will be alive in May 2020) will imcompatible with glibc 2.17? any recommend instruction to upgrade the glibc version?

**Comment by Fabcien** [comment]
Yes. You can use any previous 0.21.x release, they are all compatible with the May 2020 upgrade.
I don't have instructions for upgrading the glibc version, since this is very specific to your environment, but another approach could be to run the node inside a container or a virtual machine.
