### ISSUE TITLE
Possible Edge Case

### ISSUE THREAD

**Issue by FreeTrade** [Bitcoin-ABC/bitcoin-abc#38]
Not sure if this accounted for, but what if some mischievous actor mines a block directly after the mandatory large block that is 'back in time' so that the second block occurs before the trigger date. Would another large block then be required ?

Code in validation.cpp

 if (IsUAHFenabled(config, pindexPrev)) {
        // If UAHF is enabled for the curent block, but not for the previous
        // block, we must check that the block is larger than 1MB.
if (!IsUAHFenabled(config, pindexPrev->pprev)) {

**Comment by NiKiZe** [comment]
What about transactions to fill this first block? Since full replay protection was implemented it will mean that "lots of" transactions for BCC must be generated starting from the "last legacy block" ? (well they could be pre-generated of course and then broadcast once they are needed. (maybe this should be a different issue, and maybe it has already been taken care of - if so I'm sorry for the noise)

**Comment by FreeTrade** [comment]
Definitely there is some code there that creates a big transaction/block when required.

**Comment by deadalnix** [comment]
No, MTP must move forward, it is a consensus rule already. And there is code to generate a big block when needed by stuffing the coinbase when there isn't enough transaction in the mempool.
