### ISSUE TITLE
My Bitcoin ABC:0.20.0(EB32.0) is stuck on block 635270

### ISSUE THREAD

**Issue by mtb-pro** [Bitcoin-ABC/bitcoin-abc#388]
Please help
My bch full node  stuck on block 635270
how to fix it?

**Comment by jasonbcox** [comment]
Sounds like you may have forgotten to update in time for the May 15th protocol upgrade. Please see instructions here: https://medium.com/bitcoin-abc/how-to-upgrade-your-bitcoin-cash-node-with-bitcoin-abc-53aba2f7196c

**Comment by mtb-pro** [comment]
i use accounting but this feature has been removed in higher versions

**Comment by jasonbcox** [comment]
That's correct. Accounts have been deprecated for quite some time (since 0.20.6): https://github.com/Bitcoin-ABC/bitcoin-abc/releases/tag/v0.20.6
And it was removed entirely in 0.21.2: https://github.com/Bitcoin-ABC/bitcoin-abc/releases/tag/v0.21.2

If you need to rely on accounts for some time, you could update to 0.21.1 to be in sync with the network, migrate to labels, and then update to a later version.

**Comment by mtb-pro** [comment]
The following tutorial Worked 

https://medium.com/bitcoin-abc/how-to-upgrade-your-bitcoin-cash-node-with-bitcoin-abc-53aba2f7196c

I update to bitcoin-abc-0.21.1 and then run with `bitcoind -deprecatedrpc=accounts`
