### ISSUE TITLE
After updating to 0.21.7 RPC Connection is being refused

### ISSUE THREAD

**Issue by makeholer** [Bitcoin-ABC/bitcoin-abc#389]
Just updated from 0.19.x to 0.21.7 without changing any config or anything and now when i try a external connection from my other host for using RPC i get the error "Failed to connect to xxx.xxx.xxx.xxx port xxxx: Connection refused".

Its not a firewall problem as i dont even have one, and as i said above, it was working just before the update, my bitcoin.conf is:

server=1
daemon=1
rpcuser=MYUSERNAME
rpcpassword=MYPASSWORD
rpcallowip=MY.OTHER.HOST.IP
rpcport=XXXX
prune=550
testnet=0

Any tips?

**Comment by jasonbcox** [comment]
If you're accessing this node externally, you'll want to look into the following config options in addition to what you have:
```
rpcbind
whitelist
whitebind
```
We did recently change the behavior of how these work by default. See these release notes, for example: https://github.com/Bitcoin-ABC/bitcoin-abc/releases/tag/v0.21.6

Other than that, it will be difficult to help you pinpoint the source of the issue, as there's 2000+ changes to the software since you've last updated.  If you're still having trouble, you can update incrementally until you find the version that is causing you trouble.  That will narrow the search quite a bit.

**Comment by AdamSEY** [comment]
Same issue

**Comment by AdamSEY** [comment]
Add rpcbind=0.0.0.0 or your host ip address

**Comment by makeholer** [comment]
Yes, rpcbind=(my private ip (on amazon)) worked, thanks.

**Comment by jasonbcox** [comment]
Sounds like this is resolved.
