### ISSUE TITLE
How the step to create a wallet that can be imported to cashtab?

### ISSUE THREAD

**Issue by aalfiann** [Bitcoin-ABC/bitcoin-abc#449]
**Describe the issue**
I want to create mynodewallet so I run this command
```
./bitcoin-cli createwallet "mynodewallet"
```

But I don't see the MNEMONIC / Seedphrase

My question is **How the step to create a wallet that can be imported to cashtab?**

I've read the RPC Documentation but still confusing for first time user.
There should be any tutorial for basic setup like this.

Thanks for the help.
```
What version of Bitcoin ABC are you using, where did you get it (website, self-compiled, etc)?  
I use BitcoinABC v 0.24.5 ubuntu version.

What type of machine are you observing the error on (OS/CPU and disk type)?
Ubuntu 18.04 Bionic
```

**Comment by PiRK** [comment]
Both Bitcoin ABC and CashTab use a hierachical deterministic HD seed to generate addresses and private keys. The node does not however generate  a HD seed that can be imported into CashTab, because CashTab like most crypto wallets today expects the seed format to be a BIP 39 mnemonic phrase. Bitcoin ABC does not generate a BIP39 mnemonic, and there is no way to convert the seed it generates into such a mnemonic.

You could maybe find a way to do it the other way around: generate a wallet with CashTab, take the corresponding BIP39 mnemonic, turn it into a HD seed and import it in the node's wallet with `sethdseed`.
But I do not advise to do that. You would maybe see your CashTab transactions in the node, but probably not all the node's transactions in CashTab.
