### ISSUE TITLE
Change POW algo to get chain moving

### ISSUE THREAD

**Issue by floreslorca** [Bitcoin-ABC/bitcoin-abc#47]
Since we haven't mined a block yet and at current Hash power it will take like a day or more to get to one. I propose changing the algorithm to whatever suits ViaBTC the best.

**Comment by NiKiZe** [comment]
You do realize that if such a consensus rule should be changed, it must then be rolled out to _all_ current CASH nodes and must be activated at the same time to not create another fork? I'd say that is close to impossible and the current PoW adjusting algorithm is good enough 

"If producing the last 6 block took less than 12h (based on `GetMedianTimePast()`), we keep the same difficulty." Otherwise it is adjusted.

With current estimated hashrate from pools the rate of blocks should on average be a bit more then 8 hours, Now this can of course vary greatly, but it will be more stable in a few days. I'd suggest to have some patience until then.

**Comment by deadalnix** [comment]
No and we have mined 4 blocks now. Difficulty will adjust over the next few days.
